/**
 * README & Stats Generators
 *
 * Auto-generates markdown documentation for:
 * - Per-problem README (version history table)
 * - Root README (dashboard with stats)
 * - STATS.md (detailed breakdown)
 */

import type { ProblemManifest } from '@/types';
import { difficultyBadge, formatDateForDisplay, getLanguageName } from '@/utils/filename';

/**
 * Generate a per-problem README.md from its manifest.
 *
 * Includes: title, difficulty badge, tags, link, and a
 * version history table of all submissions.
 */
/**
 * Generate a per-problem README.md from its manifest.
 *
 * Renders one solution table per programming language.
 * The default solution (isDefault=true) is bolded and starred.
 * Commit SHAs link to the GitHub commit page.
 */
export function generateProblemReadme(manifest: ProblemManifest): string {
  const badge = difficultyBadge(manifest.difficulty);
  const tagsStr = (manifest.topicTags ?? manifest.tags ?? []).map((t) => typeof t === 'string' ? `\`${t}\`` : `\`${t.name}\``).join(' ');

  let md = `# ${badge} ${manifest.title}\n\n`;
  md += `**Difficulty:** ${manifest.difficulty}  \n`;
  md += `**Tags:** ${tagsStr || '_none_'}  \n`;
  md += `**Link:** [LeetCode](${manifest.url})  \n\n`;
  md += `---\n\n`;
  md += `## 💡 Solutions\n\n`;

  if (!manifest.solutionGroups || manifest.solutionGroups.length === 0) {
    md += `_No solutions synced yet._\n`;
    return md;
  }

  md += `| Variant | Language | Runtime | Memory | Date | Default |\n`;
  md += `|---|---|---|---|---|---|\n`;

  for (const group of manifest.solutionGroups) {
    for (const sol of group.solutions) {
      const date = formatDateForDisplay(sol.createdAt);
      const runtimeStr = sol.runtimePercentile && sol.runtimePercentile > 0
        ? `${sol.runtime ?? 'N/A'} (${sol.runtimePercentile.toFixed(0)}th %ile)`
        : (sol.runtime ?? 'N/A');
      const memoryStr = sol.memoryPercentile && sol.memoryPercentile > 0
        ? `${sol.memory ?? 'N/A'} (${sol.memoryPercentile.toFixed(0)}th %ile)`
        : (sol.memory ?? 'N/A');
      const isDefaultStr = sol.isDefault ? '✅' : '❌';
      const labelDisplay = sol.isDefault
        ? `**${sol.label}** ⭐`
        : sol.label;
      const langName = getLanguageName(group.language);

      md += `| ${labelDisplay} | ${langName} | ${runtimeStr} | ${memoryStr} | ${date} | ${isDefaultStr} |\n`;
    }
  }

  md += `\n---\n\n`;
  md += `_Auto-generated by [LeetSync](https://github.com/leetsync) — never lose a submission again._\n`;

  return md;
}

/**
 * Generate the root README.md for the entire solutions repo.
 */
export function generateRootReadme(
  manifests: ProblemManifest[],
  username: string
): string {
  const totalSolved = manifests.length;
  const easy = manifests.filter((m) => m.difficulty === 'Easy').length;
  const medium = manifests.filter((m) => m.difficulty === 'Medium').length;
  const hard = manifests.filter((m) => m.difficulty === 'Hard').length;

  // Collect all unique languages and solution counts from solutionGroups
  const languages = new Set<string>();
  let totalSolutions = 0;
  for (const m of manifests) {
    for (const g of m.solutionGroups) {
      languages.add(g.language);
      totalSolutions += g.solutions.length;
    }
  }

  let md = `# 📝 LeetCode Solutions\n\n`;
  md += `> Synced with **[LeetSync](https://github.com/leetsync)** — every solution versioned, never overwritten.\n\n`;

  md += `## 📊 Stats\n\n`;
  md += `| Metric | Count |\n`;
  md += `|--------|-------|\n`;
  md += `| **Problems Solved** | ${totalSolved} |\n`;
  md += `| 🟢 Easy | ${easy} |\n`;
  md += `| 🟡 Medium | ${medium} |\n`;
  md += `| 🔴 Hard | ${hard} |\n`;
  md += `| **Total Solutions** | ${totalSolutions} |\n`;
  md += `| **Languages** | ${languages.size} |\n\n`;

  if (languages.size > 0) {
    md += `### Languages Used\n\n`;
    for (const lang of languages) {
      const count = manifests.reduce(
        (acc, m) => acc + m.solutionGroups.filter((g) => g.language === lang).reduce((s, g) => s + g.solutions.length, 0),
        0
      );
      md += `- **${getLanguageName(lang)}**: ${count} solution${count === 1 ? '' : 's'}\n`;
    }
    md += `\n`;
  }

  // Problem list
  if (manifests.length > 0) {
    md += `## 📋 Problems\n\n`;
    md += `| # | Problem | Difficulty | Solutions | Languages |\n`;
    md += `|---|---------|------------|-----------|----------|\n`;

    const sorted = [...manifests].sort((a, b) => a.number - b.number);
    for (const m of sorted) {
      const badge = difficultyBadge(m.difficulty);
      const solutionCount = m.solutionGroups.reduce((sum, g) => sum + g.solutions.length, 0);
      const langs = m.solutionGroups.map((g) => getLanguageName(g.language)).join(', ');
      const folder = `${String(m.number).padStart(4, '0')}-${m.slug}`;

      md += `| ${m.number} | [${m.title}](${folder}/README.md) | ${badge} ${m.difficulty} | ${solutionCount} | ${langs} |\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `_Last updated: ${new Date().toISOString().split('T')[0]} — auto-generated by LeetSync_\n`;

  return md;
}

/**
 * Generate STATS.md with detailed breakdown.
 */
export function generateStats(manifests: ProblemManifest[]): string {
  const totalSolved = manifests.length;
  const easy = manifests.filter((m) => m.difficulty === 'Easy').length;
  const medium = manifests.filter((m) => m.difficulty === 'Medium').length;
  const hard = manifests.filter((m) => m.difficulty === 'Hard').length;

  let totalSolutions = 0;
  const langCounts: Record<string, number> = {};
  const labelCounts: Record<string, number> = {};

  for (const m of manifests) {
    for (const g of m.solutionGroups) {
      for (const s of g.solutions) {
        totalSolutions++;
        const langName = getLanguageName(s.language);
        langCounts[langName] = (langCounts[langName] ?? 0) + 1;
        if (s.label !== 'Default') {
          labelCounts[s.label] = (labelCounts[s.label] ?? 0) + 1;
        }
      }
    }
  }

  let md = `# 📈 LeetCode Stats\n\n`;

  md += `## Overview\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Problems Solved | ${totalSolved} |\n`;
  md += `| Total Solutions | ${totalSolutions} |\n`;
  md += `| Avg Solutions per Problem | ${totalSolved > 0 ? (totalSolutions / totalSolved).toFixed(1) : 0} |\n\n`;

  md += `## Difficulty Breakdown\n\n`;
  md += `| Difficulty | Solved |\n`;
  md += `|------------|--------|\n`;
  md += `| 🟢 Easy | ${easy} |\n`;
  md += `| 🟡 Medium | ${medium} |\n`;
  md += `| 🔴 Hard | ${hard} |\n\n`;

  md += `## Language Breakdown\n\n`;
  md += `| Language | Solutions |\n`;
  md += `|----------|-----------|\n`;
  const sortedLangs = Object.entries(langCounts).sort(([, a], [, b]) => b - a);
  for (const [lang, count] of sortedLangs) {
    md += `| ${lang} | ${count} |\n`;
  }
  md += `\n`;

  if (Object.keys(labelCounts).length > 0) {
    md += `## Solution Labels Used\n\n`;
    md += `| Label | Count |\n`;
    md += `|-------|-------|\n`;
    const sortedLabels = Object.entries(labelCounts).sort(([, a], [, b]) => b - a);
    for (const [label, count] of sortedLabels) {
      md += `| ${label} | ${count} |\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `_Auto-generated by [LeetSync](https://github.com/leetsync)_\n`;

  return md;
}
