/**
 * README & Stats Generators
 *
 * Auto-generates markdown documentation for:
 * - Per-problem README (version history table)
 * - Root README (dashboard with stats)
 * - STATS.md (detailed breakdown)
 */

import type { ProblemManifest } from '@/types';
import { difficultyBadge, formatDateForDisplay, getLanguageName } from '@/utils/filename';

/**
 * Generate a per-problem README.md from its manifest.
 *
 * Includes: title, difficulty badge, tags, link, and a
 * version history table of all submissions.
 */
export function generateProblemReadme(manifest: ProblemManifest): string {
  const badge = difficultyBadge(manifest.difficulty);
  const tagsStr = manifest.tags.map((t) => `\`${t}\``).join(' ');

  let md = `# ${badge} ${manifest.title}\n\n`;
  md += `**Difficulty:** ${manifest.difficulty}  \n`;
  md += `**Tags:** ${tagsStr || '_none_'}  \n`;
  md += `**Link:** [LeetCode](${manifest.url})  \n\n`;

  md += `---\n\n`;
  md += `## Solution History\n\n`;

  if (manifest.submissions.length === 0) {
    md += `_No submissions yet._\n`;
    return md;
  }

  // Version history table
  md += `| Version | Date | Language | Runtime | Memory | Status |\n`;
  md += `|---------|------|----------|---------|--------|--------|\n`;

  for (const sub of manifest.submissions) {
    const date = formatDateForDisplay(sub.timestamp);
    const lang = getLanguageName(sub.language);
    const statusIcon = sub.status === 'Accepted' ? '✅' : '❌';
    const runtimeStr = sub.runtimePercentile > 0
      ? `${sub.runtime} (${sub.runtimePercentile.toFixed(0)}th %ile)`
      : sub.runtime;
    const memoryStr = sub.memoryPercentile > 0
      ? `${sub.memory} (${sub.memoryPercentile.toFixed(0)}th %ile)`
      : sub.memory;

    md += `| v${sub.version} | ${date} | ${lang} | ${runtimeStr} | ${memoryStr} | ${statusIcon} ${sub.status} |\n`;
  }

  md += `\n`;

  // File links
  md += `## Files\n\n`;
  for (const sub of manifest.submissions) {
    const lang = getLanguageName(sub.language);
    md += `- [\`v${sub.version}\` — ${lang}](${sub.filePath.split('/').pop()})\n`;
  }

  md += `\n---\n\n`;
  md += `_Auto-generated by [LeetSync](https://github.com/leetsync) — never lose a submission again._\n`;

  return md;
}

/**
 * Generate the root README.md for the entire solutions repo.
 */
export function generateRootReadme(
  manifests: ProblemManifest[],
  username: string
): string {
  const totalSolved = manifests.length;
  const easy = manifests.filter((m) => m.difficulty === 'Easy').length;
  const medium = manifests.filter((m) => m.difficulty === 'Medium').length;
  const hard = manifests.filter((m) => m.difficulty === 'Hard').length;

  // Collect all unique languages
  const languages = new Set<string>();
  let totalSubmissions = 0;
  for (const m of manifests) {
    for (const s of m.submissions) {
      languages.add(s.language);
      totalSubmissions++;
    }
  }

  let md = `# 📝 LeetCode Solutions\n\n`;
  md += `> Synced with **[LeetSync](https://github.com/leetsync)** — every submission versioned, never overwritten.\n\n`;

  md += `## 📊 Stats\n\n`;
  md += `| Metric | Count |\n`;
  md += `|--------|-------|\n`;
  md += `| **Problems Solved** | ${totalSolved} |\n`;
  md += `| 🟢 Easy | ${easy} |\n`;
  md += `| 🟡 Medium | ${medium} |\n`;
  md += `| 🔴 Hard | ${hard} |\n`;
  md += `| **Total Submissions** | ${totalSubmissions} |\n`;
  md += `| **Languages** | ${languages.size} |\n\n`;

  if (languages.size > 0) {
    md += `### Languages Used\n\n`;
    for (const lang of languages) {
      const count = manifests.reduce(
        (acc, m) => acc + m.submissions.filter((s) => s.language === lang).length,
        0
      );
      md += `- **${getLanguageName(lang)}**: ${count} submission${count === 1 ? '' : 's'}\n`;
    }
    md += `\n`;
  }

  // Problem list
  if (manifests.length > 0) {
    md += `## 📋 Problems\n\n`;
    md += `| # | Problem | Difficulty | Solutions | Languages |\n`;
    md += `|---|---------|------------|-----------|----------|\n`;

    const sorted = [...manifests].sort((a, b) => a.number - b.number);
    for (const m of sorted) {
      const badge = difficultyBadge(m.difficulty);
      const solutionCount = m.submissions.length;
      const langs = [...new Set(m.submissions.map((s) => getLanguageName(s.language)))].join(', ');
      const folder = `${String(m.number).padStart(4, '0')}-${m.slug}`;

      md += `| ${m.number} | [${m.title}](problems/${folder}/README.md) | ${badge} ${m.difficulty} | ${solutionCount} | ${langs} |\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `_Last updated: ${new Date().toISOString().split('T')[0]} — auto-generated by LeetSync_\n`;

  return md;
}

/**
 * Generate STATS.md with detailed breakdown.
 */
export function generateStats(manifests: ProblemManifest[]): string {
  const totalSolved = manifests.length;
  const easy = manifests.filter((m) => m.difficulty === 'Easy').length;
  const medium = manifests.filter((m) => m.difficulty === 'Medium').length;
  const hard = manifests.filter((m) => m.difficulty === 'Hard').length;

  let totalSubmissions = 0;
  let totalAccepted = 0;
  const langCounts: Record<string, number> = {};

  for (const m of manifests) {
    for (const s of m.submissions) {
      totalSubmissions++;
      if (s.status === 'Accepted') totalAccepted++;
      const langName = getLanguageName(s.language);
      langCounts[langName] = (langCounts[langName] ?? 0) + 1;
    }
  }

  let md = `# 📈 LeetCode Stats\n\n`;

  md += `## Overview\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Problems Solved | ${totalSolved} |\n`;
  md += `| Total Submissions | ${totalSubmissions} |\n`;
  md += `| Accepted Submissions | ${totalAccepted} |\n`;
  md += `| Acceptance Rate | ${totalSubmissions > 0 ? ((totalAccepted / totalSubmissions) * 100).toFixed(1) : 0}% |\n\n`;

  md += `## Difficulty Breakdown\n\n`;
  md += `| Difficulty | Solved |\n`;
  md += `|------------|--------|\n`;
  md += `| 🟢 Easy | ${easy} |\n`;
  md += `| 🟡 Medium | ${medium} |\n`;
  md += `| 🔴 Hard | ${hard} |\n\n`;

  md += `## Language Breakdown\n\n`;
  md += `| Language | Submissions |\n`;
  md += `|----------|-------------|\n`;
  const sortedLangs = Object.entries(langCounts).sort(([, a], [, b]) => b - a);
  for (const [lang, count] of sortedLangs) {
    md += `| ${lang} | ${count} |\n`;
  }
  md += `\n`;

  md += `---\n\n`;
  md += `_Auto-generated by [LeetSync](https://github.com/leetsync)_\n`;

  return md;
}
